spring:
  freemarker:
    template-loader-path: "classpath:templates"
    suffix: ".html"
  datasource:
    url: "jdbc:postgresql://localhost:5432/max"
    username: "max"
    password: "1111"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
        format_sql: false
